### ISSUE TITLE
User to app not working

### ISSUE THREAD

**Issue by Jiddart** [rockcesar/LatinChainDevelopments#5]
Hello the payments get time out ater 60 seconds it's failed to approve please can you explain how to make this work recent version it's only state loading then after 60 seconds it show expired

**Comment by rockcesar** [comment]
@Jiddart I did a payment right now to https://test.latin-chain.com, it was successful. In this it might be a networking issue, I mean, an issue on Internet connection.

![Screenshot_20231017-123928_Pi Browser](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/38136e3e-bf4d-4bf7-95f3-3c4426134219)
![Screenshot_20231017-123953_Pi Browser](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/e77557de-6bd2-4e45-bdaa-f710f7a85e0e)

In the case of https://latin-chain.com, we are still waiting for Mainnet App wallet to receive payments.

In the case that you are using it in your own app, you need to set the values at Model: admin.apps at the menu Config Admin Pi Apps->Admin Pi App. To approve and complete payments you need to set admin_key in your own app, never publish it anywhere!.

**Comment by rockcesar** [comment]
@Jiddart Ok, I understand you want to make our code works locally or in your server. Then you need to set the minimal variables at the menu Config Admin Pi Apps->Admin Pi App, being you as admin. You to set the value for variable: admin_key

Here is the Menu:

![Screenshot_20231017-125439_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/2b127ef4-a356-4df3-be1e-d4c7316bbc42)

**Comment by rockcesar** [comment]
@Jiddart In the case you are using App Example for Pi, you need to read this:

https://github.com/rockcesar/LatinChainDevelopments/tree/master/docs-firstapp#simplest-example-for-user2app-payment

**Comment by Jiddart** [comment]
@rockcesar thanks for the reply , I'm using the code for my website the main.html and server1.php I couldn't not make them work even after putting my api key and the payment expire after 60 seconds it doesn't approve

**Comment by Jiddart** [comment]
Should I post the version of my main.html and server1.php

**Comment by rockcesar** [comment]
@Jiddart In main.html you have a field called app_client in JavaScript. In our code the value is auth_example:

![Screenshot_20231017-132500_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/c7f9f05d-1d0c-4791-8eb8-add43af709b3)

Then you need to have auth_example in the server1.php side:

![Screenshot_20231017-132554_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/2b9321f1-0e8f-4393-8761-7acad37641a2)
![Screenshot_20231017-132613_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/8974265d-37f9-4dc0-a83a-61a878c225e7)

**Comment by rockcesar** [comment]
@Jiddart You can publish it but without any sensible information as api_key.

**Comment by rockcesar** [comment]
@Jiddart Please, catch the logs and you will see the error.

**Comment by rockcesar** [comment]
@Jiddart In server1.php there is an example of a logs printing. For any error you have, you need to check your logs.

**Comment by rockcesar** [comment]
![Screenshot_20231018-050439_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/64bf5fd5-39c6-4f37-aae0-f8a12c60795e)

**Comment by Jiddart** [comment]
@rockcesar this endpoint sir
if($_POST['action'] == "approve")
    {
        $url = 'https://api.minepi.com/v2/payments/'.$_POST['paymentId'].'/approve';
        $data = array();
    }else if($_POST['action'] == "complete")
    {
        $url = 'https://api.minepi.com/v2/payments/'.$_POST['paymentId'].'/complete';
        $data = array('txid' => $_POST['txid']);
    }
    


Or should I check my error logs in cpanel to find any sir

**Comment by rockcesar** [comment]
You need to activate the logs in your server1.php file, it should appears in server.log.

![Screenshot_20231018-050439_Samsung Internet](https://github.com/rockcesar/LatinChainDevelopments/assets/5984401/4d06113a-34df-463b-9523-54f09ad42d4f)

**Comment by Jiddart** [comment]
@rockcesar  sir my server.log is like this

Accessed 2023-10-18 09:22:45

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:22:46
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error


Accessed 2023-10-18 09:22:54

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:22:55
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error


Accessed 2023-10-18 09:23:03

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:23:04
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error


Accessed 2023-10-18 09:23:13

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:23:14
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error


Accessed 2023-10-18 09:23:25

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:23:26
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error


Accessed 2023-10-18 09:23:33

_POST Array
(
    [action] => approve
    [paymentId] => k6ay86drW2qSh06uBScuEkF6Rz0k
    [txid] => 
    [app_client] => auth_example
)


Response 2023-10-18 09:23:34
{"error":"invalid_authorization","error_message":"This endpoint requires a Server API Key authorization."}
Error

**Comment by rockcesar** [comment]
@Jiddart Well there is the error. Your issue is that you have a wrong API Key.

**Comment by rockcesar** [comment]
Your api key must be setted as:

$apps['auth_example'] = 'Key your_key';

if your key is 1234567890, then it should be as:

$apps['auth_example'] = 'Key 1234567890';

**Comment by Jiddart** [comment]
@rockcesar   It's working now thank you so much I really appreciate your efforts thank you

**Comment by rockcesar** [comment]
@Jiddart Perfect!. And remember, never publish your API Key. Greetings!.
